#!/bin/sh
set -e
cd "$(git rev-parse --show-toplevel)"
gitleaks git --staged --no-banner --redact
cd server
npx prettier --check "src/**/*.ts" "test/**/*.ts"
npm run --silent lint
npx knip
npx jscpd
npx depcruise src test
npx tsc --noEmit -p tsconfig.json
npm run --silent test:cov
npx nestjs-doctor . --staged --blocking error
npx stryker run
